# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='ref_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
